version: 2.1

jobs:
  test:
    docker:
      - image: cimg/postgres:13.6
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: cimg/node:14.19
    working_directory: ~/lib
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
  release:
    docker:
      - image: cimg/node:14.19
    working_directory: ~/lib
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Release
          command: npx semantic-release@17

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: Test
          context: nodejs-install
          filters:
            branches:
              ignore:
                - main
  release:
    jobs:
      - release:
          name: Release
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - main
